#  https://j8a507.p.ssafy.io/api/login/oauth2/code/kakao
#  http://localhost:8093/login/oauth2/code/kakao

serverHost: j8a507.p.ssafy.io
#baseUrl: https://j8a507.p.ssafy.io/api
#redirectUrl: https://j8a507.p.ssafy.io
baseUrl: http://localhost:8080
redirectUrl: http://localhost:3000

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: baefcb7f3997dcd1d75094c79e124e06
            client-secret: 9pHOg3MOqGXsyPiwMp94kwND9o9wfW9T
            redirect-uri: '${baseUrl}/login/oauth2/code/kakao'
            scope:
              - account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  data:
    mongodb:
      host: ${serverHost}
      port: 27017
      authentication-database: admin
      database: peak
      username: a507
      password: dkdlehf
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  redis:
    host: ${serverHost}
    port: 6379
    database: 0
    password: dkdlehf
jwt:
  header: Authorization
  secret: kAuZ05M7rsAV39ODO7uFLNczR8Bm6GJz4+WsBC5zgUxy9EeI6kd7MnfH4VtXeioo4BLzqa8UTsGzKssFr8wHuA==
  access-token-valid-time: 1800
  refresh-token-valid-time: 604800

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG